urls.py
from flask import Blueprint, request, render_template, redirect, url_for, flash
from werkzeug.security import generate_password_hash, check_password_hash
from user_management.init import db
from user_management.models import User

urls_blueprint = Blueprint('urls', __name__, template_folder='templates')


@urls_blueprint.route('/')
def index():
    return render_template('index.html')


@urls_blueprint.route('/register', methods=['GET', 'POST'])
def register():
    if request.method == 'POST':
        username = request.form.get('username')
        password = request.form.get('password')

        if len(password) < 8:
            flash('Пароль должен содержать, как минимум 8 символов', 'danger')
            return render_template('register.html')

        existing_user = User.query.filter_by(username=username).first()
        if existing_user:
            flash('Такое имя пользователя уже существует!', 'danger')
            return render_template('register.html')

        hashed_password = generate_password_hash(password)
        new_user = User(username=username, password=hashed_password)

        db.session.add(new_user)
        db.session.commit()

        flash('Регистрация пользователя успешна!', 'success')

        # Очистка полей формы регистрации
        return render_template('register.html')

    return render_template('register.html')


@urls_blueprint.route('/login', methods=['GET', 'POST'])
def login():
    if request.method == 'POST':
        username = request.form.get('username')
        password = request.form.get('password')

        user = User.query.filter_by(username=username).first()
        if not user or not check_password_hash(user.password, password):
            return render_template('login.html', message='Ошибка входа. Пожалуйста проверьте ваш никнейм и пароль.')

        return redirect(url_for('urls.get_users'))

    return render_template('login.html')


@urls_blueprint.route('/users')
def get_users():
    users = User.query.all()
    return render_template('users.html', users=users)

user_management/models.py
from user_management.init import db


class User(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    username = db.Column(db.String(100), unique=True, nullable=False)
    password = db.Column(db.String(100), nullable=False)

templates/add_user.html
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Добавить пользователя</title>
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" rel="stylesheet">
</head>
<body>
    <div class="container mt-5">
        <h1>Добавить пользователя</h1>
        {% if message %}
            <div class="alert alert-success">{{ message }}</div>
        {% endif %}
        <form method="POST">
            <div class="form-group">
                <label for="username">Имя пользователя:</label>
                <input type="text" class="form-control" id="username" name="username" required>
            </div>
            <div class="form-group">
                <label for="password">Пароль:</label>
                <input type="password" class="form-control" id="password" name="password" required>
            </div>
            <button type="submit" class="btn btn-primary">Добавить пользователя</button>
        </form>
        <a href="/users" class="mt-3 d-block">К списку пользователей</a>
    </div>
</body>
</html>

templates/index.html
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Домашняя страница</title>
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" rel="stylesheet">
</head>
<body>
    <div class="container mt-5">
        <h1>Добро пожаловать на домашнюю страницу</h1>
        <a href="/register" class="btn btn-primary mr-2">Регистрация</a>
        <a href="/login" class="btn btn-primary">Вход</a>
    </div>
</body>
</html>

templates/login.html
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Вход</title>
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" rel="stylesheet">
</head>
<body>
    <div class="container mt-5">
        <h1>Страница входа</h1>
        {% if message %}
            <div class="alert alert-danger">{{ message }}</div>
        {% endif %}
        <form method="POST" action="{{ url_for('urls.login') }}">
            <div class="form-group">
                <label for="username">Имя пользователя:</label>
                <input type="text" class="form-control" id="username" name="username" required>
            </div>
            <div class="form-group">
                <label for="password">Пароль:</label>
                <input type="password" class="form-control" id="password" name="password" required>
            </div>
            <button type="submit" class="btn btn-primary">Войти</button>
        </form>
        <a href="{{ url_for('urls.index') }}" class="mt-3 d-block">На главную</a>
    </div>
</body>
</html>

templates/register.html
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Регистрация</title>
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" rel="stylesheet">
</head>
<body>
<div class="container mt-5">
    <h1>Страница регистрации</h1>
    {% with messages = get_flashed_messages(with_categories=False) %}
        {% if messages %}
            <div class="alert alert-success">
                {% for message in messages %}
                    {{ message }}
                {% endfor %}
            </div>
        {% endif %}
    {% endwith %}
    <form method="POST" action="{{ url_for('urls.register') }}">
        <div class="form-group">
            <label for="username">Имя пользователя:</label>
            <input type="text" class="form-control" id="username" name="username" required>
        </div>
        <div class="form-group">
            <label for="password">Пароль:</label>
            <input type="password" class="form-control" id="password" name="password" required>
        </div>
        <button type="submit" class="btn btn-primary">Зарегистрироваться</button>
    </form>
    <a href="{{ url_for('urls.index') }}" class="mt-3 d-block">На главную</a>
</div>
</body>
</html>

templates/update_user.html
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Изменить пользователя</title>
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" rel="stylesheet">
</head>
<body>
    <div class="container mt-5">
        <h1>Изменить пользователя</h1>
        {% if message %}
            <div class="alert alert-success">{{ message }}</div>
        {% endif %}
        <form method="POST">
            <div class="form-group">
                <label for="username">Имя пользователя:</label>
                <input type="text" class="form-control" id="username" name="username" value="{{ user.username }}" required>
            </div>
            <div class="form-group">
                <label for="password">Новый пароль:</label>
                <input type="password" class="form-control" id="password" name="password" required>
            </div>
            <button type="submit" class="btn btn-primary">Изменить пользователя</button>
        </form>
        <a href="{{ url_for('get_users') }}" class="mt-3 d-block">К списку пользователей</a>
    </div>
</body>
</html>

templates/users.html
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Пользователи</title>
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" rel="stylesheet">
</head>
<body>
    <div class="container mt-5">
        <h1>Список пользователей</h1>
        <a href="/user/add" class="btn btn-primary mb-3">Добавить пользователя</a>
        {% if message %}
            <div class="alert alert-success">{{ message }}</div>
        {% endif %}
        <ul class="list-group">
            {% for user in users %}
                <li class="list-group-item d-flex justify-content-between align-items-center">
                    {{ user.username }}
                    <div>
                        <a href="/user/{{ user.id }}/update" class="btn btn-sm btn-warning mr-2">Изменить</a>
                        <form action="/user/{{ user.id }}/delete" method="POST" style="display: inline;">
                            <button type="submit" class="btn btn-sm btn-danger">Удалить</button>
                        </form>
                    </div>
                </li>
            {% endfor %}
        </ul>
        <a href="{{ url_for('urls.index') }}" class="mt-3 d-block">На главную</a>
    </div>
</body>
</html>